let json = {
  agreement: "AGREEMENT",
  confidence: "100",
  irony: "NONIRONIC",
  model: "general_en",
  score_tag: "N+",
  sentence_list: [
    {
      agreement: "AGREEMENT",
      bop: "y",
      confidence: "100",
      endp: "257",
      inip: "0",
      score_tag: "N+",
      segment_list: [
        {
          agreement: "AGREEMENT",
          confidence: "100",
          endp: "257",
          inip: "0",
          polarity_term_list: [
            {
              confidence: "100",
              endp: "128",
              inip: "125",
              score_tag: "N+",
              sentimented_concept_list: [
                {
                  endp: "38",
                  form: "avenger",
                  id: "65fdadcbff",
                  inip: "31",
                  score_tag: "N+",
                  type: "Top\u003ePerson",
                  variant: "Avengers",
                },
              ],
              sentimented_entity_list: [
                {
                  endp: "24",
                  form: "country of Sokovia",
                  id: "__3518487553365751806",
                  inip: "7",
                  score_tag: "N+",
                  type: "Top\u003eLocation\u003eGeoPoliticalEntity\u003eCountry",
                  variant: "country of Sokovia",
                },
                {
                  endp: "51",
                  form: "Iron Man",
                  id: "529e97f38e",
                  inip: "42",
                  score_tag: "N+",
                  type: "Top\u003eProduct\u003eCulturalProduct\u003eMovie",
                  variant: "Tony Stark",
                },
                {
                  endp: "65",
                  form: "Steve Rogers",
                  id: "2418af20d6",
                  inip: "54",
                  score_tag: "N+",
                  type: "Top\u003ePerson\u003eFullName",
                  variant: "Steve Rogers",
                },
                {
                  endp: "71",
                  form: "Thor",
                  id: "5f8b6e87d6",
                  inip: "68",
                  score_tag: "N+",
                  type: "Top\u003eLocation\u003eGeoPoliticalEntity",
                  variant: "Thor",
                },
                {
                  endp: "71",
                  form: "Thor",
                  id: "8f9502a801",
                  inip: "68",
                  score_tag: "N+",
                  type: "Top\u003ePerson\u003eFirstName",
                  variant: "Thor",
                },
                {
                  endp: "85",
                  form: "Bruce Banner",
                  id: "__13726859781023558032",
                  inip: "74",
                  score_tag: "N+",
                  type: "Top",
                  variant: "Bruce Banner",
                },
                {
                  endp: "103",
                  form: "Natasha Romanoff",
                  id: "__13891153709863729564",
                  inip: "88",
                  score_tag: "N+",
                  type: "Top\u003ePerson\u003eFullName",
                  variant: "Natasha Romanoff",
                },
                {
                  endp: "121",
                  form: "Clint Barton",
                  id: "__754254597092124379",
                  inip: "110",
                  score_tag: "N+",
                  type: "Top\u003ePerson\u003eFullName",
                  variant: "Clint Barton",
                },
              ],
              text: "raid",
            },
          ],
          score_tag: "N+",
          segment_list: [
            {
              agreement: "AGREEMENT",
              confidence: "100",
              endp: "38",
              inip: "27",
              polarity_term_list: [
                {
                  confidence: "100",
                  endp: "38",
                  inip: "31",
                  score_tag: "N",
                  sentimented_concept_list: [
                    {
                      endp: "38",
                      form: "avenger",
                      id: "65fdadcbff",
                      inip: "31",
                      score_tag: "N",
                      type: "Top\u003ePerson",
                      variant: "Avengers",
                    },
                  ],
                  text: "avenger",
                },
              ],
              score_tag: "N",
              segment_type: "main",
              text: "the Avengers",
            },
            {
              agreement: "AGREEMENT",
              confidence: "100",
              endp: "173",
              inip: "130",
              polarity_term_list: [
                {
                  confidence: "100",
                  endp: "148",
                  inip: "146",
                  score_tag: "P",
                  text: "lead@V",
                },
              ],
              score_tag: "P",
              segment_type: "main",
              sentimented_entity_list: [
                {
                  endp: "173",
                  form: "Wolfgang von Strucker",
                  id: "__11421176103750650480",
                  inip: "153",
                  score_tag: "NONE",
                  type: "Top",
                  variant: "Wolfgang von Strucker",
                },
              ],
              text: "a Hydra outpost led by Wolfgang von Strucker",
            },
          ],
          segment_type: "main",
          sentimented_entity_list: [
            {
              endp: "256",
              form: "Loki",
              id: "__14053569387950304116",
              inip: "253",
              score_tag: "NONE",
              type: "Top\u003ePerson\u003eFullName",
              variant: "Loki",
            },
            {
              endp: "173",
              form: "Wolfgang von Strucker",
              id: "__11421176103750650480",
              inip: "153",
              score_tag: "NONE",
              type: "Top",
              variant: "Wolfgang von Strucker",
            },
          ],
          text: "In the country of Sokovia, the Avengers – Tony Stark, Steve Rogers, Thor, Bruce Banner, Natasha Romanoff, and Clint Barton – raid a Hydra outpost led by Wolfgang von Strucker, who has been experimenting on humans using the scepter previously wielded by Loki.",
        },
      ],
      sentimented_concept_list: [
        {
          form: "avenger",
          id: "65fdadcbff",
          score_tag: "N+",
          type: "Top\u003ePerson",
        },
      ],
      sentimented_entity_list: [
        {
          form: "Steve Rogers",
          id: "2418af20d6",
          score_tag: "N+",
          type: "Top\u003ePerson\u003eFullName",
        },
        {
          form: "Iron Man",
          id: "529e97f38e",
          score_tag: "N+",
          type: "Top\u003eProduct\u003eCulturalProduct\u003eMovie",
        },
        {
          form: "Thor",
          id: "5f8b6e87d6",
          score_tag: "N+",
          type: "Top\u003eLocation\u003eGeoPoliticalEntity",
        },
        {
          form: "Thor",
          id: "8f9502a801",
          score_tag: "N+",
          type: "Top\u003ePerson\u003eFirstName",
        },
        {
          form: "Loki",
          id: "__14053569387950304116",
          score_tag: "NONE",
          type: "Top\u003ePerson\u003eFullName",
        },
        {
          form: "Wolfgang von Strucker",
          id: "__11421176103750650480",
          score_tag: "NONE",
          type: "Top",
        },
        {
          form: "Bruce Banner",
          id: "__13726859781023558032",
          score_tag: "N+",
          type: "Top",
        },
        {
          form: "Natasha Romanoff",
          id: "__13891153709863729564",
          score_tag: "N+",
          type: "Top\u003ePerson\u003eFullName",
        },
        {
          form: "country of Sokovia",
          id: "__3518487553365751806",
          score_tag: "N+",
          type: "Top\u003eLocation\u003eGeoPoliticalEntity\u003eCountry",
        },
        {
          form: "Clint Barton",
          id: "__754254597092124379",
          score_tag: "N+",
          type: "Top\u003ePerson\u003eFullName",
        },
      ],
      text: "In the country of Sokovia, the Avengers – Tony Stark, Steve Rogers, Thor, Bruce Banner, Natasha Romanoff, and Clint Barton – raid a Hydra outpost led by Wolfgang von Strucker, who has been experimenting on humans using the scepter previously wielded by Loki.",
    },
    {
      agreement: "AGREEMENT",
      bop: "n",
      confidence: "100",
      endp: "472",
      inip: "259",
      score_tag: "N",
      segment_list: [
        {
          agreement: "AGREEMENT",
          confidence: "100",
          endp: "343",
          inip: "259",
          polarity_term_list: [],
          score_tag: "NONE",
          segment_type: "secondary",
          sentimented_concept_list: [
            {
              endp: "310",
              form: "twin",
              id: "0e35ad0409",
              inip: "306",
              score_tag: "NONE",
              type: "Top\u003ePerson",
              variant: "twins",
            },
            {
              endp: "310",
              form: "twin",
              id: "93f89a8a84",
              inip: "306",
              score_tag: "NONE",
              type: "Top\u003ePerson",
              variant: "twins",
            },
            {
              endp: "343",
              form: "speed",
              id: "e50498110e",
              inip: "339",
              score_tag: "NONE",
              type: "Top\u003eUnit\u003eSpeedUnit",
              variant: "speed",
            },
          ],
          sentimented_entity_list: [
            {
              endp: "317",
              form: "Pietro",
              id: "__13802492502779249448",
              inip: "312",
              score_tag: "NONE",
              type: "Top\u003ePerson",
              variant: "Pietro",
            },
            {
              endp: "288",
              form: "Strucker",
              id: "d2624f89ad",
              inip: "281",
              score_tag: "NONE",
              type: "Top\u003ePerson\u003eLastName",
              variant: "Strucker",
            },
          ],
          text: "They encounter two of Strucker's experiments – twins Pietro, who has superhuman speed",
        },
        {
          agreement: "AGREEMENT",
          confidence: "100",
          endp: "433",
          inip: "350",
          polarity_term_list: [
            {
              confidence: "100",
              endp: "383",
              inip: "370",
              score_tag: "N",
              sentimented_entity_list: [
                {
                  endp: "363",
                  form: "Wanda Maximoff",
                  id: "__16858144557084070716",
                  inip: "350",
                  score_tag: "N",
                  type: "Top\u003ePerson\u003eFullName",
                  variant: "Wanda Maximoff",
                },
                {
                  endp: "433",
                  form: "Strucker",
                  id: "d2624f89ad",
                  inip: "426",
                  score_tag: "N",
                  type: "Top\u003ePerson\u003eLastName",
                  variant: "Strucker",
                },
              ],
              text: "manipulate",
            },
          ],
          score_tag: "N",
          segment_type: "main",
          sentimented_concept_list: [
            {
              endp: "408",
              form: "energy",
              id: "b606e89e91",
              inip: "403",
              score_tag: "NONE",
              type: "Top",
              variant: "energy",
            },
            {
              endp: "401",
              form: "project",
              id: "bde52a085f",
              inip: "395",
              score_tag: "NONE",
              type: "Top",
              variant: "project",
            },
          ],
          text: "Wanda Maximoff, who can manipulate minds and project energy – and apprehend Strucker",
        },
        {
          agreement: "AGREEMENT",
          confidence: "100",
          endp: "471",
          inip: "436",
          polarity_term_list: [],
          score_tag: "NONE",
          segment_type: "secondary",
          sentimented_entity_list: [
            {
              endp: "446",
              form: "Stark",
              id: "633a3ea48b",
              inip: "442",
              score_tag: "NONE",
              type: "Top\u003ePerson\u003eLastName",
              variant: "Stark",
            },
            {
              endp: "461",
              form: "Loki",
              id: "__14053569387950304116",
              inip: "458",
              score_tag: "NONE",
              type: "Top\u003ePerson\u003eFullName",
              variant: "Loki",
            },
          ],
          text: "while Stark retrieves Loki's scepter",
        },
      ],
      sentimented_concept_list: [
        {
          form: "twin",
          id: "0e35ad0409",
          score_tag: "NONE",
          type: "Top\u003ePerson",
        },
        {
          form: "twin",
          id: "93f89a8a84",
          score_tag: "NONE",
          type: "Top\u003ePerson",
        },
        {
          form: "energy",
          id: "b606e89e91",
          score_tag: "NONE",
          type: "Top",
        },
        {
          form: "project",
          id: "bde52a085f",
          score_tag: "NONE",
          type: "Top",
        },
        {
          form: "speed",
          id: "e50498110e",
          score_tag: "NONE",
          type: "Top\u003eUnit\u003eSpeedUnit",
        },
      ],
      sentimented_entity_list: [
        {
          form: "Stark",
          id: "633a3ea48b",
          score_tag: "NONE",
          type: "Top\u003ePerson\u003eLastName",
        },
        {
          form: "Loki",
          id: "__14053569387950304116",
          score_tag: "NONE",
          type: "Top\u003ePerson\u003eFullName",
        },
        {
          form: "Pietro",
          id: "__13802492502779249448",
          score_tag: "NONE",
          type: "Top\u003ePerson",
        },
        {
          form: "Wanda Maximoff",
          id: "__16858144557084070716",
          score_tag: "N",
          type: "Top\u003ePerson\u003eFullName",
        },
        {
          form: "Strucker",
          id: "d2624f89ad",
          score_tag: "N",
          type: "Top\u003ePerson\u003eLastName",
        },
      ],
      text: "They encounter two of Strucker's experiments – twins Pietro, who has superhuman speed, and Wanda Maximoff, who can manipulate minds and project energy – and apprehend Strucker, while Stark retrieves Loki's scepter.",
    },
  ],
  sentimented_concept_list: [
    {
      form: "twin",
      id: "0e35ad0409",
      score_tag: "NONE",
      type: "Top\u003ePerson",
    },
    {
      form: "avenger",
      id: "65fdadcbff",
      score_tag: "N+",
      type: "Top\u003ePerson",
    },
    {
      form: "twin",
      id: "93f89a8a84",
      score_tag: "NONE",
      type: "Top\u003ePerson",
    },
    { form: "energy", id: "b606e89e91", score_tag: "NONE", type: "Top" },
    { form: "project", id: "bde52a085f", score_tag: "NONE", type: "Top" },
    {
      form: "speed",
      id: "e50498110e",
      score_tag: "NONE",
      type: "Top\u003eUnit\u003eSpeedUnit",
    },
  ],
  sentimented_entity_list: [
    {
      form: "Steve Rogers",
      id: "2418af20d6",
      score_tag: "N+",
      type: "Top\u003ePerson\u003eFullName",
    },
    {
      form: "Iron Man",
      id: "529e97f38e",
      score_tag: "N+",
      type: "Top\u003eProduct\u003eCulturalProduct\u003eMovie",
    },
    {
      form: "Thor",
      id: "5f8b6e87d6",
      score_tag: "N+",
      type: "Top\u003eLocation\u003eGeoPoliticalEntity",
    },
    {
      form: "Stark",
      id: "633a3ea48b",
      score_tag: "NONE",
      type: "Top\u003ePerson\u003eLastName",
    },
    {
      form: "Thor",
      id: "8f9502a801",
      score_tag: "N+",
      type: "Top\u003ePerson\u003eFirstName",
    },
    {
      form: "Loki",
      id: "__14053569387950304116",
      score_tag: "NONE",
      type: "Top\u003ePerson\u003eFullName",
    },
    {
      form: "Wolfgang von Strucker",
      id: "__11421176103750650480",
      score_tag: "NONE",
      type: "Top",
    },
    {
      form: "Bruce Banner",
      id: "__13726859781023558032",
      score_tag: "N+",
      type: "Top",
    },
    {
      form: "Pietro",
      id: "__13802492502779249448",
      score_tag: "NONE",
      type: "Top\u003ePerson",
    },
    {
      form: "Natasha Romanoff",
      id: "__13891153709863729564",
      score_tag: "N+",
      type: "Top\u003ePerson\u003eFullName",
    },
    {
      form: "Wanda Maximoff",
      id: "__16858144557084070716",
      score_tag: "N",
      type: "Top\u003ePerson\u003eFullName",
    },
    {
      form: "country of Sokovia",
      id: "__3518487553365751806",
      score_tag: "N+",
      type: "Top\u003eLocation\u003eGeoPoliticalEntity\u003eCountry",
    },
    {
      form: "Clint Barton",
      id: "__754254597092124379",
      score_tag: "N+",
      type: "Top\u003ePerson\u003eFullName",
    },
    {
      form: "Strucker",
      id: "d2624f89ad",
      score_tag: "N",
      type: "Top\u003ePerson\u003eLastName",
    },
  ],
  status: {
    code: "0",
    msg: "OK",
    credits: "1",
    remaining_credits: "19998",
  },
  subjectivity: "OBJECTIVE",
};

module.exports = json;
