import "./resets.scss";
import "./base.scss";
import "./header.scss";
import "./main.scss";
import "./footer.scss";
import "./form.scss";
import "./result.scss";
import "./spinner.scss";
import "./alert.scss";
